### ISSUE TITLE
Verify that the custom Emscripten FS from JupyterLite can be used

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voici#3]
### Problem

JupyterLite can provide access to local files using a custom Emscripten File System, we should check that Voilite works properly with it

**Comment by jtpio** [comment]
Just checked with Voici 0.2.0 via the [Voici Demo](https://github.com/voila-dashboards/voici-demo) and it appears the Service Worker can't be found.

This looks like an issue with the base URL:

![image](https://user-images.githubusercontent.com/591645/224636351-46ec2b86-2c93-4fdf-b3bc-4bc6067ff6dd.png)

**Comment by jtpio** [comment]
Checking with the `demo` folder, it appears that the `baseUrl` in the initial `jupyter-config-data` is empty:

![image](https://user-images.githubusercontent.com/591645/231372092-52ec5332-dd49-4d0b-939c-9ff221fb56a4.png)

But manually setting `"baseUrl": "/"` in the generated HTML seems to do the trick:

![image](https://user-images.githubusercontent.com/591645/231373120-4a541c97-b24d-412c-b517-eee6204ba5f4.png)

**Comment by jtpio** [comment]
That empty string looks unexpected since there the `baseUrl` is currently set to `/` here:

https://github.com/voila-dashboards/voici/blob/8069c958e257c1a5781a33bc2e632b6a8fde8392/voici/addon.py#L142-L145

**Comment by jtpio** [comment]
As a comparison the `themesUrl` defined here:

https://github.com/voila-dashboards/voici/blob/bfb048b9f3a8e3a0124c953d089aa3816d9c029d/voici/tree_exporter.py#L52-L54

Appears to be defined correctly on the page:

![image](https://user-images.githubusercontent.com/591645/231406110-fed8de51-d77d-432a-9d12-f679390cc9da.png)

@martinRenou do you know if the page config `baseUrl` might be overridden at some other point during the export, maybe in an upstream exported?

**Comment by martinRenou** [comment]
> @martinRenou do you know if the page config baseUrl might be overridden at some other point during the export, maybe in an upstream exported?

It's not impossible that Voila itself overrides the baseUrl?

**Comment by jtpio** [comment]
Right, I'm not exactly sure how the empty `baseUrl` is ended up on the page:

![image](https://user-images.githubusercontent.com/591645/231372092-52ec5332-dd49-4d0b-939c-9ff221fb56a4.png)

However, this seems to be triggering the following code path in JupyterLab `PageConfig`:

https://github.com/jupyterlab/jupyterlab/blob/25658adabce206725cafe42161181ba43ae87bcd/packages/coreutils/src/pageconfig.ts#L37-L39

```ts
export function getOption(name: string): string {
    if (configData) {
      return configData[name] || getBodyData(name);
    }
```

`configData[name]` would be `""`, so the `||` triggers a call to `getBodyData`. With `getBodyData` getting the value from the `body` data attribute:

![image](https://user-images.githubusercontent.com/591645/231524278-51086134-75ec-43b0-aa88-3eb7c847b9d4.png)


Which `voila` defines here: https://github.com/voila-dashboards/voila/blob/0f4cc5360ff387eeaf7e647cee712b2ce08d573a/share/jupyter/voila/templates/base/page.html#L23

```html
 <body data-base-url="{{ base_url }}voila/">
```

Most likely that's why there is a  `voila/` part in the URL:

![image](https://user-images.githubusercontent.com/591645/224636351-46ec2b86-2c93-4fdf-b3bc-4bc6067ff6dd.png)

**Comment by jtpio** [comment]
Digging a bit more, Voila seems to be updating the page config `baseUrl` with the one from the `resources`: https://github.com/voila-dashboards/voila/blob/0f4cc5360ff387eeaf7e647cee712b2ce08d573a/share/jupyter/voila/templates/lab/index.html.j2#L81

```jinja
{# Set a dummy variable - we just want the side effect of the update. #}
{% set _ = page_config_full.update(baseUrl=resources.base_url, kernelId=kernel_id) %}
```

So if `resources.base_url` is empty, that could explain why we always get `"baseUrl": ""`.
